<?php

namespace Database\Seeders;

use App\Models\QueueTicket;
use Illuminate\Database\Seeder;

class QueueDemoSeeder extends Seeder
{
    public function run(): void
    {
        $tickets = [
            [
                'external_reference' => 'demo-queue-001',
                'patient_name' => 'Nguyễn Văn An',
                'channel' => QueueTicket::CHANNEL_COUNTER,
                'service_type' => QueueTicket::SERVICE_BHYT,
                'department' => QueueTicket::DEPARTMENT_INSURANCE,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PENDING,
                'status' => QueueTicket::STATUS_WAITING_PAYMENT,
                'estimated_wait' => 28,
                'notes' => 'Chờ xác nhận quyền lợi BHYT.',
                'created_at' => now()->subMinutes(42),
            ],
            [
                'external_reference' => 'demo-queue-002',
                'patient_name' => 'Trần Thị Hạnh',
                'channel' => QueueTicket::CHANNEL_KIOSK,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_INTERNAL,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_READY,
                'estimated_wait' => 20,
                'notes' => 'Khám tổng quát định kỳ.',
                'activated_at' => now()->subMinutes(25),
                'created_at' => now()->subMinutes(35),
            ],
            [
                'external_reference' => 'demo-queue-003',
                'patient_name' => 'Lê Minh Khôi',
                'channel' => QueueTicket::CHANNEL_WEB,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_CARDIOLOGY,
                'priority_level' => 3,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_READY,
                'estimated_wait' => 12,
                'notes' => 'Người bệnh từ đủ 75 tuổi trở lên.',
                'activated_at' => now()->subMinutes(18),
                'created_at' => now()->subMinutes(30),
            ],
            [
                'external_reference' => 'demo-queue-004',
                'patient_name' => 'Phạm Gia Bảo',
                'channel' => QueueTicket::CHANNEL_COUNTER,
                'service_type' => QueueTicket::SERVICE_CAP_CUU,
                'department' => QueueTicket::DEPARTMENT_EMERGENCY,
                'priority_level' => 5,
                'payment_status' => QueueTicket::PAYMENT_EXEMPTED,
                'status' => QueueTicket::STATUS_CALLING,
                'estimated_wait' => 0,
                'notes' => 'Đau ngực, khó thở, cần xử trí ngay.',
                'activated_at' => now()->subMinutes(10),
                'called_at' => now()->subMinutes(2),
                'created_at' => now()->subMinutes(14),
            ],
            [
                'external_reference' => 'demo-queue-005',
                'patient_name' => 'Võ Thị Thu',
                'channel' => QueueTicket::CHANNEL_PHONE,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_ENT,
                'priority_level' => 2,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_SERVING,
                'estimated_wait' => 0,
                'notes' => 'Phụ nữ có thai, được ưu tiên theo quy định.',
                'activated_at' => now()->subMinutes(32),
                'called_at' => now()->subMinutes(16),
                'created_at' => now()->subMinutes(40),
            ],
            [
                'external_reference' => 'demo-queue-006',
                'patient_name' => 'Đỗ Quốc Việt',
                'channel' => QueueTicket::CHANNEL_COUNTER,
                'service_type' => QueueTicket::SERVICE_BHYT,
                'department' => QueueTicket::DEPARTMENT_INTERNAL,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_MISSED,
                'estimated_wait' => 0,
                'notes' => 'Đã gọi nhưng bệnh nhân chưa có mặt.',
                'activated_at' => now()->subMinutes(28),
                'called_at' => now()->subMinutes(12),
                'missed_at' => now()->subMinutes(9),
                'no_show_at' => now()->subMinutes(9),
                'created_at' => now()->subMinutes(38),
            ],
            [
                'external_reference' => 'demo-queue-007',
                'patient_name' => 'Bùi Ngọc Mai',
                'channel' => QueueTicket::CHANNEL_KIOSK,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_PEDIATRICS,
                'priority_level' => 3,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_READY,
                'estimated_wait' => 8,
                'notes' => 'Trẻ em dưới 6 tuổi.',
                'activated_at' => now()->subMinutes(12),
                'created_at' => now()->subMinutes(22),
            ],
            [
                'external_reference' => 'demo-queue-008',
                'patient_name' => 'Hoàng Đức Long',
                'channel' => QueueTicket::CHANNEL_WEB,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_CARDIOLOGY,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_COMPLETED,
                'estimated_wait' => 0,
                'notes' => 'Đã hoàn tất khám buổi sáng.',
                'activated_at' => now()->subHours(2),
                'called_at' => now()->subHours(1)->subMinutes(35),
                'completed_at' => now()->subHours(1)->subMinutes(18),
                'created_at' => now()->subHours(2)->subMinutes(12),
            ],
            [
                'external_reference' => 'demo-queue-009',
                'patient_name' => 'Ngô Hải Yến',
                'channel' => QueueTicket::CHANNEL_COUNTER,
                'service_type' => QueueTicket::SERVICE_BHYT,
                'department' => QueueTicket::DEPARTMENT_INSURANCE,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_COMPLETED,
                'estimated_wait' => 0,
                'notes' => 'Đã hoàn tất quy trình khám BHYT.',
                'activated_at' => now()->subHours(3),
                'called_at' => now()->subHours(2)->subMinutes(40),
                'completed_at' => now()->subHours(2)->subMinutes(20),
                'created_at' => now()->subHours(3)->subMinutes(18),
            ],
            [
                'external_reference' => 'demo-queue-010',
                'patient_name' => 'Đặng Thanh Tùng',
                'channel' => QueueTicket::CHANNEL_PHONE,
                'service_type' => QueueTicket::SERVICE_DICH_VU,
                'department' => QueueTicket::DEPARTMENT_INTERNAL,
                'priority_level' => 0,
                'payment_status' => QueueTicket::PAYMENT_PAID,
                'status' => QueueTicket::STATUS_CANCELLED,
                'estimated_wait' => 0,
                'notes' => 'Bệnh nhân chủ động hủy lượt khám.',
                'activated_at' => now()->subMinutes(55),
                'created_at' => now()->subMinutes(70),
            ],
        ];

        foreach ($tickets as $index => $ticket) {
            QueueTicket::updateOrCreate(
                ['external_reference' => $ticket['external_reference']],
                array_merge($ticket, [
                    'ticket_number' => $index + 1,
                    'queue_number' => QueueTicket::makeQueueNumber($index + 1, $ticket['department']),
                ]),
            );
        }
    }
}
